import type { Scene, Project, ShotListItem, StoryboardFrame } from '../types'

/**
 * Generate a markdown document for the cinematic package
 */
export function generatePackageMarkdown(project: Project, scene: Scene): string {
  const lines: string[] = []

  // Header
  lines.push(`# ${project.title}`)
  lines.push(`**Genre:** ${project.genre}`)
  lines.push(`**Visual Style:** ${project.visualStyle}`)
  lines.push('')
  lines.push('---')
  lines.push('')

  // Scene Info
  lines.push(`## Scene ${scene.order}`)
  lines.push('')
  lines.push(`### Logline`)
  lines.push(scene.logline || '_No logline generated_')
  lines.push('')

  // Refined Scene
  lines.push(`### Refined Scene`)
  lines.push(scene.refinedScene || scene.rawInput)
  lines.push('')

  // Shot List
  if (scene.shotList.length > 0) {
    lines.push(`### Shot List`)
    lines.push('')
    lines.push('| Shot | Type | Movement | Lens | Lighting | Description | Notes |')
    lines.push('|------|------|----------|------|----------|-------------|-------|')
    scene.shotList.forEach((shot: ShotListItem) => {
      lines.push(`| ${shot.shotNumber} | ${shot.shotType} | ${shot.cameraMovement} | ${shot.lens} | ${shot.lighting} | ${shot.description} | ${shot.notes} |`)
    })
    lines.push('')
  }

  // Storyboard
  if (scene.storyboardFrames.length > 0) {
    lines.push(`### Storyboard Frames`)
    lines.push('')
    scene.storyboardFrames.forEach((frame: StoryboardFrame) => {
      lines.push(`**Frame ${frame.frameNumber}:** ${frame.shotType} - ${frame.cameraMove}`)
      lines.push(`> ${frame.description}`)
      if (frame.imageUrl) {
        lines.push(`![Frame ${frame.frameNumber}](${frame.imageUrl})`)
      }
      lines.push('')
    })
  }

  // Audio Mood
  if (scene.audioMood) {
    lines.push(`### Audio Design`)
    lines.push('')
    lines.push(`**Genre:** ${scene.audioMood.genre}`)
    lines.push(`**Tempo:** ${scene.audioMood.tempo}`)
    lines.push(`**Mood:** ${scene.audioMood.mood}`)
    lines.push(`**Instruments:** ${scene.audioMood.instruments.join(', ')}`)
    lines.push('')
    lines.push(`**Generation Prompt:**`)
    lines.push(`> ${scene.audioMood.promptForGeneration}`)
    lines.push('')
  }

  // Motion Teaser
  if (scene.motionTeaserPrompt) {
    lines.push(`### Motion Teaser Prompt`)
    lines.push('')
    lines.push(`> ${scene.motionTeaserPrompt}`)
    lines.push('')
  }

  // Style Memory
  lines.push(`### Style Memory`)
  lines.push('')
  lines.push(`**Tone:** ${project.styleMemory.tone}`)
  lines.push(`**Visual Style:** ${project.styleMemory.visualStyle}`)
  lines.push(`**Camera Language:** ${project.styleMemory.cameraLanguage}`)
  lines.push(`**Pace:** ${project.styleMemory.paceDescriptor}`)
  lines.push(`**Emotional Arc:** ${project.styleMemory.emotionalArc}`)
  if (project.styleMemory.colorPalette.length > 0) {
    lines.push(`**Color Palette:** ${project.styleMemory.colorPalette.join(', ')}`)
  }
  if (project.styleMemory.recurringMotifs.length > 0) {
    lines.push(`**Recurring Motifs:** ${project.styleMemory.recurringMotifs.join(', ')}`)
  }
  lines.push('')

  // Footer
  lines.push('---')
  lines.push('*Generated by DirectorOS — Agentic AI Filmmaking*')
  lines.push('*Big Screen Hack 2026 | Theme: INTO THE UNKNOWN*')

  return lines.join('\n')
}

/**
 * Download content as a file
 */
export function downloadFile(content: string, filename: string, mimeType: string = 'text/markdown'): void {
  const blob = new Blob([content], { type: mimeType })
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = filename
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
  URL.revokeObjectURL(url)
}

/**
 * Copy text to clipboard
 */
export async function copyToClipboard(text: string): Promise<boolean> {
  try {
    await navigator.clipboard.writeText(text)
    return true
  } catch {
    return false
  }
}
